(add-to-list 'auto-mode-alist '(".rb" . enh-ruby-mode))
(add-to-list 'auto-mode-alist '(".scss" . scss-mode))
(add-to-list 'auto-mode-alist '(".rake" . enh-ruby-mode))
(add-to-list 'auto-mode-alist '(".ru" . ruby-mode))
(add-to-list 'auto-mode-alist '("Gemfile" . enh-ruby-mode))
(add-to-list 'auto-mode-alist '("Guardfile" . enh-ruby-mode))
(add-to-list 'auto-mode-alist '("Rakefile" . enh-ruby-mode))
(add-to-list 'auto-mode-alist '(".stumpwmrc'" . stumpwm-mode))
(add-to-list 'auto-mode-alist '(".hamlbars'" . haml-mode))
(add-to-list 'auto-mode-alist '(".hamlc'" . haml-mode))
(provide 'my-add-to-lists)
