(smex-initialize)
(icomplete-mode)
(ido-mode t)
(ido-ubiquitous-mode t)
(winner-mode)
(go-to-hell-bars)
(recentf-mode t)
(show-paren-mode t)
(highline-mode 1)
(auto-compression-mode 1)
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)

(provide 'my-initializers)
